### ISSUE TITLE
"SyntaxError: redeclaration of let BotGUI" in Firefox 60

### ISSUE THREAD

**Issue by Two-Tone** [ensingm2/saliengame_idler#20]
I don't get this error in Chromium, but do in FF (my main browser).

**Comment by ensingm2** [comment]
When is it triggered? Page load?

**Comment by Two-Tone** [comment]
Sorry, forgot to include that info!   It's triggered immediately after inputting the script.

**Comment by ensingm2** [comment]
You sure you aren't running any extensions or anything? I just tested 60.0.2 and it's working fine for me.

Also, are you using the most recent version?

EDIT: I _can_ get that error by copying the script in twice without refreshing. That might be another thing to make sure isn't happening.

**Comment by Two-Tone** [comment]
I figured it out, it's user error.  I had first accidentally input the
script at the start screen then later tried doing it at one of the
planets.  So the error was because I was trying to declare BotGUI a second
time.

Oops.
