### ISSUE TITLE
Stopped Progressing (Stuck on Zone?)

### ISSUE THREAD

**Issue by playlaughlovelearn** [ensingm2/saliengame_idler#21]
At some point I stopped progressing: I tried re-loading to no avail. 

Here's what I think might be the relevant console messages:

     #TerritoryControl_PlanetBehind_the_Screen - Zone 75 Progress: 0.9954538941383362 Difficulty: 3
     Zone #75 has ended. Trying #75
     Round successfully started in zone #75

Maybe 75 is complete but is never actually reporting 100% on the check?

**Comment by Harest** [comment]
Hi,

I assume you were still using a relatively old script where the grid wasn't refresh before switching to another zone. That's why it try to go back to the same zone because the game still think it's the best one.

**Comment by playlaughlovelearn** [comment]
Hmm, well, like I said, I reloaded the app, and re-pasted the script, so I would have figured that manually reset it (also I only started using it a few hours ago so I think I already had the grid load fix), but it was still stuck on the same zone. 

I ran for a bit with an extra conditional in GetBestZone to make sure the zone.progress < 99.0 which caused it to switch zones finally although I have taken that back out and it still seems to have moved on. So, maybe there was just some glitch on Steam's end that's worked out now, or maybe refreshing didn't reset the grid? I think I went around 30 minutes with it continually saying "Zone #75 has ended. Trying #75" (and getting no XP) before I reloaded everything, and then it continued that way for another 5 minutes or so before I posted.

Anyway can't reproduce currently. Thanks for the response. :)

**Comment by Harest** [comment]
Which script did you re-paste ? If you still have it, ctrl + f `INJECT_update_grid`. If there's no result you've the answer ^^. I'm almost certain the update that happened +/- 8 hours ago fix this issue. At least i had many switchs that happened without any issue on my side.  
Be sure to report again if you've an issue of that sort. We should probably add an header with the version or something to help in these cases to know the version used.

**Comment by playlaughlovelearn** [comment]
I had made a copy to add my progress check, and it does have INJECT_update_grid... I would suggest adding the progress check to the script but I'm not 100% certain that's what caused it to move on since the main script is working fine again on that planet.

Also, as an additional note, it's switched nodes since then just fine, so whatever it was is very intermittent.

**Comment by Draco18s** [comment]
I had this problem once yesterday, and what fixed it was loading the planet, then loading into a "battle", *then* starting the script. As the current state was "combat," it picked up from there and was fine afterwards.

**Comment by ensingm2** [comment]
I _believe_ this should be fixed now with some of the changes made last night/this morning. Closing the issue for now, feel free to re-open if it happens again.
