### ISSUE TITLE
The timer doesn't seem to work properly.

### ISSUE THREAD

**Issue by ambjorn0** [ensingm2/saliengame_idler#28]
I'm running 2 accounts side by side and the timer doesn't add up.
On account1 I'm lvl 10 with ~1970000 xp with time left to level up at 10h 50m
On account2 I'm lvl 10 with ~1280000 xp with time left to level up at 4h 40m

Both in same difficulty target zone.

![desktop screenshot](https://user-images.githubusercontent.com/29261575/41811345-5199c3f0-770e-11e8-9372-e834b3ce361e.png)

**Comment by ambjorn0** [comment]
And yes I tried reloading everything a few times.

**Comment by Protolando** [comment]
I get a lower time in a lvl 1 zone then in a level 2 zone, with the same account. It still auto-picks the level 2 one.

**Comment by ambjorn0** [comment]
in 50 minutes the timer for account1 has gone down by about 15 minutes while the timer for account2 seems to keep up properly.

**Comment by ensingm2** [comment]
If those two scripts are indeed on the same difficulty planets, there should be no difference in the get_max_Score() function they run. Can anyone confirm this is still an issue?

There _will_ be some inaccuracy, just from the fact that the estimate assumes you will be running zones of your current difficulty forever, and they won't run out.

**Comment by Nikai-san** [comment]
Lvl Up In doesn't show how much days left til level up. account2's timer should look as "1d 4h 40m" instead of "4h 40m".

**Comment by ensingm2** [comment]
@Nikai-san Yup that's a problem. Should be fixed now with 0bacc991efe40d611b071ae637e8a349b517164e. Thanks!

**Comment by ensingm2** [comment]
Going to close this issue as I believe it's about as accurate as it can be, without doing rolling avg exp gain or guessing future exp rates.

If someone still believes the timers to be incorrectly calculating, feel free to re-open this, or create a new issue.
