### ISSUE TITLE
Map Graphical Update

### ISSUE THREAD

**Issue by Draco18s** [ensingm2/saliengame_idler#29]
It would be nice if the zone map could update periodically (after a tile is complete).

It's great that there's the progress shown display that was added recently, rather than it being all console statements. Though I would like to see the tiles fill in as they are completed, as a Nice To Have.

**Comment by ensingm2** [comment]
I _want_ to say this should be a thing now, with the non-disabled animations. The old grid hovers are re-enabled, and I believe by default those values update periodically.

**Comment by Draco18s** [comment]
I grabbed the latest script all of 10 minutes before making the issue and the grid hover wasn't working.
Did it change more recently than that?

**Comment by ensingm2** [comment]
Yup!

**Comment by Draco18s** [comment]
That does it then, woo.
Of course, the added window stacks on top of the game-tile-tooltip for the upper left corner, but at least its an HTML object I can firebug it out of the way if I need to see those tiles.

**Comment by ensingm2** [comment]
Actually, I should probably fix that as well.

Edit: ...At Some point. whole game canvas is a single layer so I can't just one-line z-index it. Will need to find somewhere out of the way for it to live.
