### ISSUE TITLE
EXP/level stat not updating

### ISSUE THREAD

**Issue by asdfCYBER** [ensingm2/saliengame_idler#4]
Not really an issue, but when adding the visual feedback feature, might be worth looking at

**Comment by ensingm2** [comment]
Yeah, it's on the todo list to force that update. The page doesn't expect you to gain exp while at the menu so I couldn't get it working quickly. Leaving this issue open until I can get around to it tonight.

**Comment by ensingm2** [comment]
"Fixed" in https://github.com/ensingm2/saliengame_idler/pull/14 & following hotfix with custom gui.
