### ISSUE TITLE
Does not automatically restart after completion

### ISSUE THREAD

**Issue by t-booden** [ensingm2/saliengame_idler#42]
When a zone has been completed, it stays on the "Searching for zone" screen, and I have to manually refresh the browser and then put in the code again.

**Comment by ensingm2** [comment]
Working on this now, actually. Think I know the issue.

**Comment by ensingm2** [comment]
Hoping this is fixed in 8a3a7d4c926ed43bd585f6686dbf93ef406e320b. Let me know if not. I'll likely close this issue if there aren't any complaints tomorrow.

**Comment by Reina-Orikasa** [comment]
The new branch works for me at least. There's a _slight_ delay (2 score send attempts) but it worked and sent me to a new sector. 

Apparently it's having trouble switching from hard to medium. I needed a browser reset for that.

**Comment by t-booden** [comment]
Neat, it switched a zone when the zone got completed.
I do not know yet about the issue Reina here says, but I am happy this issue got fixed.

**Comment by ensingm2** [comment]
Closing this issue, feel free to re-open if it happens again.
