### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by gyrospizzeria** [ensingm2/saliengame_idler#47]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://community.steam-api.com/ITerritoryControlMinigameService/ReportScore/v0001/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Is this a problem with firefox or am I doing something wrong?

**Comment by gyrospizzeria** [comment]
Switched to chrome and now get these errors:

- jquery-1.11.1.min.js?v=.isFTSRckeNhC:4 Failed to load https://community.steam-api.com/ITerritoryControlMinigameService/GetPlanet/v0001/?id=13: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://steamcommunity.com' is therefore not allowed access.

    network.js?v=ktu7gGAyXBfO&l=english:212 Uncaught ReferenceError: error is not defined
    at Object.<anonymous> (network.js?v=ktu7gGAyXBfO&l=english:212)
    at j (jquery-1.11.1.min.js?v=.isFTSRckeNhC:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1.min.js?v=.isFTSRckeNhC:2)
    at x (jquery-1.11.1.min.js?v=.isFTSRckeNhC:4)
    at XMLHttpRequest.b (jquery-1.11.1.min.js?v=.isFTSRckeNhC:4)

**Comment by Harest** [comment]
We're aware of this issue. It's a Steam server-side issue afaik. Sometimes the required header in the API response isn't there. I made a pull request (#46) to improve how errors are handled so it can eventually avoid the script to stop. Not sure we can do much more.

**Comment by ensingm2** [comment]
PR merged in, hopefully this will let us keep going, despite steam server hiccups. Closing this for now, if the issue pops up again, feel free to re-open.
