### ISSUE TITLE
Add live-toggling of animations

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/saliengame_idler#49]
Disabling animations currently breaks a lot of stuff in the UI, so you can't simply re-enable the function to my knowledge.

We should find a way to  hook the function and can run it selectively, potentially decreasing the refresh rate, but at the very least allowing an explicit enable/disable toggle.

**Comment by LoneDev6** [comment]
Added on #63

**Comment by ensingm2** [comment]
Nice! I need to make a couple small changes and test, but if this works correctly I'll merge it in after work today.

**Comment by ensingm2** [comment]
Merged in #63. Closing issue.
