### ISSUE TITLE
Server Error: Script still said ✓ Running

### ISSUE THREAD

**Issue by Draco18s** [ensingm2/saliengame_idler#51]
I forgot to catch the error that was displayed, all I know is that Chrome had crashed (taking down one account with Meepen's script) and Firefox's instance was still "green" but when I looked at it more closely I saw that it was reporting a server error and was not active, but the status still read "✓ Running" in green, so I don't even know how long it had been like that (I was occasionally glancing at it and seeing the green status and going "cool" and tabbing away again).

Error was something along the lines of "too many ____" (e.g. too many connections, too many instances, something like that).

**Comment by Harest** [comment]
Error handling has been added since, and it's relatively similar to your other issue reported in #58. Closing it.
