### ISSUE TITLE
Seems Boss update broke script entirely

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/saliengame_idler#70]
Getting stuck on waiting 5s as the joins are failing, due to

> X-eresult: 17
X-error_message: This is a boss zone. Update your cheats.

Nice, valve.

Unfortunately I'm on vacation and won't be able to modify this much. I can merge in PRs and test, though.

**Comment by Harest** [comment]
Yeah that's why i pointed out an update to do in the op of #69 to not join a zone where boss = true for now.  
Edit : I did the update. Should be fixed.

**Comment by Dontmindme2** [comment]
I think it goes further than that.  There is a bad zone on one of the planets (top left).  You cannot even enter it manually without a script, but it reads "High".  I wonder if this zone will become a future boss.  Boss may not show as "true" yet.  It may be waiting for enough other zones to be conquered first.

**Comment by Harest** [comment]
Hum, okay. I also found it strange when i was on this planet that it said it was a boss zone and when i called JoinBossZone on it, it said it wasn't a boss zone (in the header errormessage). I guess they messed up their code a little there.

**Comment by Dontmindme2** [comment]
Or it's intentional as a place-holder until conquering enough other zones activates it.  So, there needs to be a distinction for "future" boss zone and current.  At least we have an idea where the next boss zone is going to be...

**Comment by ensingm2** [comment]
Seems like they messed up something with Glory Days II Zone 0. It's not listed as a boss zone, but will return errors if you try to join. Even manually trying to launch that zone with no scripts running will error out the game client. My bet is it'll resolve when valve realizes they messed up their zone array and updates.

**Comment by mibbio** [comment]
Some other script has a temporary fix (skip zone 0 if there is no progress) for this issue. https://github.com/meepen/salien-bot/issues/149#issuecomment-401518355

**Comment by matforest** [comment]
Thanks mibbio, I've worked around that issue by changing line 554 to this:
`if (!zone.captured && !zone.boss && zone.progress > 0) {`

Seems to be working ok, haven't exactly tested it much though 🤷


edit: line 554, not 555

**Comment by Arxero** [comment]
@matforest it is actually 554, and yes, for now, it works thank you. : -)

**Comment by ensingm2** [comment]
Introduced @matforest's quick fix with bf663f8ca51d0f1989ca19f7cd11dc81e301fa65. This issue should be good for now (or at least worked around).
