### ISSUE TITLE
Stop Boss Fight Before hitting Level 25?

### ISSUE THREAD

**Issue by Dontmindme2** [ensingm2/saliengame_idler#74]
I have noticed that the badge rank and sale item drops don't appear from level-ups during the boss fights.  But when I leveled up on regular fights this morning, I received the new rank and all the sale items I didn't get earlier.

What that means is that as we approach the highest level (25), we probably don't want to cross the level threshold during a boss fight (if you care about badge rank or sale items).  Otherwise, we may never see the new rank or items if all our level-ups came during the boss fights.  Maybe Valve will fix this bug on their end, maybe they won't.  I didn't get Rank 4 until I hit a new level the non-boss way, and I just hit 21 in another boss fight and don't see the Rank 6 badge or sale item.

But it shouldn't be that hard to program in a disconnect shortly before we hit 26,400,000 XP.  That way we can finish up the last bit through normal fights.

**Comment by Harest** [comment]
This (#76) should do the job ([you can test it](https://raw.githubusercontent.com/ensingm2/saliengame_idler/26136e1318738adf394150c36329db42fa44c576/idle.js) if you want). I'll let it open for eventual peer-reviewing and merge it later on.

**Comment by Dontmindme2** [comment]
Looks good.  Of course I still need "a few" levels to properly test it.

**Comment by Harest** [comment]
Yeah i reached lvl 21 on the last boss, 25 is pretty far away for now, until some bosses spawn on hard zones.  
Edit : I think i just got the lvl 21 item. I guess they still check and give level-based items every now and then. It wasn't much to add anyway.

**Comment by Dontmindme2** [comment]
Still no badge rank or item for me.  I had jumped from 15 to 19 yesterday, but didn't get any of the items or badge rank until I leveled to 20.

**Comment by Dontmindme2** [comment]
Weird, not sure if Valve fixed it, but got both items immediately during the boss battle as I hit 22.

**Comment by Harest** [comment]
I think i'll remove the "improvement". Main reason is you get a bonus xp when the boss die apparently. And i don't know how much is it, it seems to vary. I think they're giving items anyway, with some delay eventually but they do.

**Comment by Dontmindme2** [comment]
Fine to remove it, seems Valve fixed the drop problem.  Every level drop started coming immediately, all boss fights.
