### ISSUE TITLE
Possible error on brand new planet

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/saliengame_idler#78]
I believe this error stems from the fix for issue #70. I _think_ if you planet switch to a completely fresh planet, no 'best' zone is found (as we limit to zones with progress), as no zones have any progress yet.

**Comment by Harest** [comment]
Yes i already witnessed this (and commented on #73).  And i decided to do a fix just now, i'll merge it. Until now i let the unlock function does its job after 5 min.  
Edit : Here, fixed.

**Comment by ensingm2** [comment]
Are you sure this was fixed with PR #73? I was getting the issue when testing earlier today, working off master (should've been after that was merged in, I believe). 

May have very well been one of those steam server-side issues that have been happening, though.

**Comment by Harest** [comment]
I meant i commented in one of the commits that's in #73. And i added [a quick fix](https://github.com/ensingm2/saliengame_idler/commit/71ef7e345edda05de2c7c4a78b1da21fedf0d0fe) earlier for it.

**Comment by ensingm2** [comment]
Ah, got it. I assume this is good to close out, then?

**Comment by Harest** [comment]
Yep.
