### ISSUE TITLE
High mem- and cpu usage

### ISSUE THREAD

**Issue by Zazcallabah** [ensingm2/saliengame_idler#8]
This isn't a problem with the script, but rather with the game. On the other hand, it would be nice to not have a laptop that almost overheats while it idly "plays" a browser game. 

I solved the problem by simply setting `requestAnimationFrame = null` in the debugger before pasting the script. It solves the overheating problem, with the downside that the interface no longer updates.

**Comment by ensingm2** [comment]
Hopefully (mostly) fixed with https://github.com/ensingm2/saliengame_idler/pull/9

Closing issue, feel free to re-open if it's still a problem.
