### ISSUE TITLE
Disable timer of estimate time

### ISSUE THREAD

**Issue by JeanPaulLucien** [ensingm2/saliengame_idler#82]
I don't need this info and tried to create a checkbox to disable this funtion. Doesn't work. If you wish to finish that, I have create the checkbox for you. Check this: https://github.com/ensingm2/saliengame_idler/pull/80/commits/a1d4415bbc6e0bab9aa7068019d74950d06cbe5e

**Comment by ensingm2** [comment]
Adding a checkbox to toggle the display of this feature results in the same number of rows when disabled, and an extra when enabled, so only adds additional clutter. Closing this issue
