### ISSUE TITLE
After Boss battle ends, the script doesn't update the EXP value in info box

### ISSUE THREAD

**Issue by anjari** [ensingm2/saliengame_idler#87]
As title said, the EXP value in info box is not updated when the boss battle is over. Although this is a minor issue, it could lead to misunderstanding that the boss battle doesn't give EXP at all.

---

I also have a question, how optimal the boss battle script for gaining the EXP? I heard some salien scripts put too high damage which makes the boss battle ends too fast thus getting lower EXP.

**Comment by ensingm2** [comment]
~Script does about 4 dps on average. While this is about 20x the steamdb value, it's still negligible~ This seems outdated, looking to be more in the .5-1dps range now (For reference, the boss I'm currently on has 110 Million health and is taking a bit over a million dps). I have a feeling boss HP decays over time regardless of player damage. Once boss HP dropped below 100M damage taken decreased significantly, which shouldn't happen normally.

As far as updating exp on leaving a boss battle, yeah I'd agree it should probably be added.

**Comment by JeanPaulLucien** [comment]
I'm in Boss Battle, will wait for end.

Ih this script there is calc for damage based on boss HP, if you wish may try my fork with little mod for this math func. I'm interesting how it works, or not.

@ensingm2 what about to add damage to results in Boss Battle?

**Comment by JeanPaulLucien** [comment]
> As title said, the EXP value in info box is not updated when the boss battle is over. Although this is a minor issue, it could lead to misunderstanding that the boss battle doesn't give EXP at all.

Works well. Updated after fight and later reported about new level.

**Comment by Jap2-0** [comment]
Is all EXP given at the end of the boss battle, or is it also given when you die?

**Comment by JeanPaulLucien** [comment]
> Is all EXP given at the end of the boss battle, or is it also given when you die?

I didn't die.

**Comment by Jap2-0** [comment]
> > Is all EXP given at the end of the boss battle, or is it also given when you die?

> I didn't die.

I wasn't asking if you had died.  I was asking when you get XP from boss fights.

**Comment by JeanPaulLucien** [comment]
> **after fight**

I don't know how it works when die. So, I wrote:

> I didn't die.

**Comment by ensingm2** [comment]
@JeanPaulLucien You're getting notifications because you commented on this issue, it's not a question directed just at you, so you shouldn't feel the need to respond.

@Jap2-0 It gives you exp during the fight, every ~5 seconds when the reportbossdamage call is made.

**Comment by Harest** [comment]
The XP obtained is still granted no matter what. So you can die without losing anything, except maybe getting no or a little less bonus xp (not sure on that though).  
About the OP, i stated my point of view in the related PR #88 :  
> I thought about updating the current xp and stuff during bosses but it didn't seem worth it. _The end is nigh._  

To elaborate a little more, to do it correctly we would need to check if we leveled up and if yes displaying the next xp step for the next level. It's not really that long but considering it'll be updated with the next non-boss round, i found it too unnecessary to do it myself. If anyone wants to do it, feel free. Just need to do an array with the xp required for each level and do the checks / updates of the GUI.

**Comment by ensingm2** [comment]
Closing this out as the exp counter now updates during the boss fight. Even if it doesn't update again at the end, it should be up to date from the final tick. Re-open if people find that's not the case.
