### ISSUE TITLE
Damage in Boss Battle

### ISSUE THREAD

**Issue by JeanPaulLucien** [ensingm2/saliengame_idler#89]
I know we told about before. Actually script does 0 - 20 damage. 

What about this algotithm:
_damage = math.floor(math.random * 1000 / boss_lost_hp)

So, than more boss has lost hp, then less damage.

**Comment by Harest** [comment]
[It doesn't do 0-20](https://github.com/ensingm2/saliengame_idler/commit/3ebd169a1ff341452d1929cf8d8cfa329076ee00). The first time it'll deal between 0-19, and then it's based on the boss max hp  / 9 000 000.  
E.g. : A boss with 110 000 000 HP -> Damages range will be 0-12. One with 500M, it'll be 0-55.  
Everything is explained as to why i did this in the commit. With a typo : *fair, not fait.

**Comment by ensingm2** [comment]
Closing as this is a non-issue.
