### ISSUE TITLE
Disable joining to zone for 25 lvls

### ISSUE THREAD

**Issue by JeanPaulLucien** [ensingm2/saliengame_idler#90]
If player is 25 lvls he doesn't need more xp. So, we can just stay on the planet screen for timer and stay xp for players who didn't received 25 lvl.

**Comment by Harest** [comment]
You don't need a script for that i think.. ?

**Comment by JeanPaulLucien** [comment]
@Harest, maybe, but scrtipt switches planet and helps in boss battle to other players.

**Comment by Harest** [comment]
It doesn't really help, if you join a boss battle, you're still leeching, until you do 0 damage. I think the xPaw script is now doing this. With 1 damage at the beginning to be eligible to get bonus xp.  
The purpose of the script is to get XP anyway. If you don't need XP anymore, the script doesn't have much use. I don't think this will be modified.  
To enter giveaways, you just need to do 1 battle on the planet. I'd suggest to simply use `CEnemyManager.prototype.BuildEnemy = function(){};` in the console without anything else and joining a zone.

**Comment by ensingm2** [comment]
Closing, as agreed with @Harest
