### ISSUE TITLE
Join Planet Error

### ISSUE THREAD

**Issue by asdfCYBER** [ensingm2/saliengame_idler#91]
Occasionally a 'Join Planet Error' popup pops up which blocks user input but does not stop the script.

**Comment by ensingm2** [comment]
Huh, thought I undid this bug when I rolled back my 'fix' for #84. Regardless, the script still functions behind that error popup, and the game is only going on for a little over another hour I believe, so this probably won't be fixed.

Regardless, thanks for the report!
